### ISSUE TITLE
Phoenix - Pairoscope - Region to be skipped - Structural Variant - Exome -TumorOnly

### ISSUE THREAD

**Issue by ChristopheLegendre** [tgen/jetstream_resources#49]
### Phoenix - Pairoscope - Region to be skipped - Structural Variant - Exome -TumorOnly

New MYC Region to be skipped in Pairsocope (aka mm_igtx_pairsocope)
`chr8:128,452,800-128,453,150`

This exact region of non-specific alignment is present in the 20 CANDOR samples I have looked into IGV.
In order to minimize potential issues with the tool pairoscope, we need to blank out this region.

Screenshot:
![Screen Shot 2021-01-05 at 15 43 50](https://user-images.githubusercontent.com/2623980/103707974-de535e80-4f6c-11eb-9197-54f996046f31.png)

**Comment by bryce-turner** [comment]
This is handled directly in Phoenix, closing this issue as it has been resolved already on the Phoenix repo.
