### ISSUE TITLE
Suncity Capture_kits.csv

### ISSUE THREAD

**Issue by PedalheadPHX** [tgen/jetstream_resources#64]
Make sure active version has: 

TE2,Twist_Exome_2.0,Twist_hg19_exome_v2.0.2_targets_sorted_validated.annotated_0_ContigCorrected.bed,Twist_hg19_exome_v2.0.2_targets_sorted_validated.annotated_0_ContigCorrected.bed

**Comment by bryce-turner** [comment]
Fixed in f0f83ae
